### ISSUE TITLE
Fields should be case insensetive

### ISSUE THREAD

**Issue by amuzalevskiy** [perry-mitchell/ads.txt#2]

**Comment by andrewmolyuk** [comment]
`Field #1` and `Field #3` should be treated as case insensitive.

References:
- https://iabtechlab.com/wp-content/uploads/2017/09/IABOpenRTB_Ads.txt_Public_Spec_V1-0-1.pdf
- https://tools.ietf.org/html/rfc1034

**Comment by perry-mitchell** [comment]
@andrewmolyuk So you mean the domain and the account type? I get the account type being case insensitive, but in what way do you mean the domain should be? Are you saying that it should be checked for case-insensitive uniqueness when _building_ a new file, or?

**Comment by perry-mitchell** [comment]
Closed by #3. Released in 0.2.1. Thanks!
